### ISSUE TITLE
setAccount should be removed

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/contracts#134]
The `setAccount` function can be used to change the balance between two users. It can be called by the owner of the contract only, and doesn't require approval from the users involved.

In other words users need to trust the contract owners to not mess with the balances. AFAICT this is not acceptable.

Currently the function is only being used for testing.

**Comment by berndbohmeier** [comment]
This is for setting up a network by the operator. It will later only be accessable during bootstrap phase, see #90.

**Comment by andfletcher** [comment]
Done.
