### ISSUE TITLE
Evaluate SafeMath

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/contracts#18]
The following things are either redundant or I maybe do not understand the usage: 

- https://github.com/trustlines-network/contracts/blob/master/contracts/lib/SafeMath.sol#L34
  should be redudant, division by zero should throw anyways
- https://github.com/trustlines-network/contracts/blob/master/contracts/lib/SafeMath.sol#L36
  What does that check, this should always hold
- https://github.com/trustlines-network/contracts/blob/master/contracts/lib/SafeMath.sol#L36
  Why not use overloading?
- https://github.com/trustlines-network/contracts/blob/master/contracts/lib/SafeMath.sol#L85
  not sure what you try to check here, this should be always true
- https://github.com/trustlines-network/contracts/blob/master/contracts/lib/SafeMath.sol#L115
  what do you try to test here? if a and by are integers that does not make sense

Overall it is confusing again the usage of assert. Do you try to prevent something(then please dont name it assert) or do you just double check something what should be right (should not be used to prevent overflows, because ofcourse they can happen).

**Comment by andfletcher** [comment]
Outdated.
