### ISSUE TITLE
Create currency network registry contract

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/contracts#228]
- [x] do not use plain mappings only
- [x] should be only "addable" (no delete or change)
- [x] add event for new created entries
- [x] this will not be used by other contracts
- [x] the names for a currency network are not unique, but the address is the identifier

Additional requirements after clarification
- [x] Implements ERC-165
- [x] Stores author / adding address
- [x] Stores CurrencyNetwork Metadata
- [x] Entries can not be overwritten

**Comment by saschagoebel** [comment]
Some questions that came up when writing the initial code:

- Should we store who added the network to the registry? We can also get that information from the chain directly.

- Should we store any metadata for the network at all? We could just relay calls to the network contract itself without any gas cost (getName, getSymbol, ...)

- Would it make sense to move some of the metadata of the network contract into the interface, so people would be required to give that information? I'm thinking of the "token" properties at least.

- Alternatively we could also implement ERC-165 and/or EIP 1046 for Metadata retrieval.

Thoughts @weilbith @cducrest ?

**Comment by cducrest** [comment]
> Should we store who added the network to the registry? We can also get that information from the chain directly.

Yes we should.

> Should we store any metadata for the network at all? We could just relay calls to the network contract itself without any gas cost (getName, getSymbol, ...)

I would just store it. But you can do as you want I guess.

> Would it make sense to move some of the metadata of the network contract into the interface, so people would be required to give that information? I'm thinking of the "token" properties at least.

If you decide to use them in the registry, sure.

> Alternatively we could also implement ERC-165 and/or EIP 1046 for Metadata retrieval.

I don't want to spend time reading these, but if it is not much more work just do it.

> It should be forbidden to "overwrite" a once added network

Yes.

> Should we check if the network fulfills the interface somehow?

No.

The current idea is that we cannot prevent abuse, which is the reason why for example Bernd believe it is useless. We decided to implement it anyway to stop talking about it.
