### ISSUE TITLE
ReferralReward Distribution

### ISSUE THREAD

**Issue by heikoheiko** [trustlines-protocol/contracts#29]
To incentify `CurrencyNetwork` users to onboard other users, a referral reward is introduced, which is applied transitively.

Note: As onboarder and onboarded only differ in the last character, also `Oldiver` and `Newton` might be used.

### Logic

1. The `ReferralReward` contract stores all data relevant to be able to reward the onboarder:
`mapping onboarded => (onboarded, blocknumber)`
2. Onboarders can be rewarded from fees payed by the ones they onboarded. Note his only happens if triggered, before there is an overflow of the`feesOutstanding` field in a trustline. 
3. The reward process can be recursive, the Oldiver also gets a share of the fees Newton gets from the fees of the ones he onboarded. 

_Note: Onborders can not be payed from outstanding fees, if the trustline is cut._

**Comment by andfletcher** [comment]
We have implemented onboarding tracking and reward part will be done later (the different issue has been created)
