### ISSUE TITLE
Upgrading CurrencyNetworks

### ISSUE THREAD

**Issue by ice09** [trustlines-protocol/contracts#31]
## Requirement

A `CurrencyNetwork` must be updateable in case of errors or necessary functionality updates. All data in the contract (ie. the Trustlines) must be preserved during the update.

## Solutions

Possible solutions are listed here: https://github.com/trustlines-network/contracts/blob/master/docs/NonFuncReqs.md the`EternalStorage` solution is preferred for readability and maintainability, but will be too costly (is currently evaluated)

An alternative would be the use of the `DELEGATECALL` in combination with the `Proxy` or `user-account`. The implementation is currently used by uPort.
_NOTE: By introducing the `Proxy`, uPort wants to make sure to be able to exchange the `user-account` in case it has errors._ 

![tl-onboarding 2](https://user-images.githubusercontent.com/2828581/28863289-99aa429c-7768-11e7-9c24-5e07f42f2aa2.png)

1.  A `user-account` and a `Proxy` are created when a new user joins a network.
2. The `Proxy` address is the official user account address, ie. the `chain-account`
3. The  `user-account` delegates to a `Proxy`, which calls the `CurrencyNetwork` functions using `DELEGATECALL` (preserving `msg.sender` of the `controller`) <- not sure about this, can be `CALL` as well
4. To call a `CurrencyNetwork` function, the transaction data must be submitted to the `forward` function of the `controller` 

Updates of the `ContractNetwork` can then be done by changing the destination address which is currently a parameter in the call of the `user-account` function `forward` (which is restricted to the `app-account`)

**Comment by heikoheiko** [comment]
Q: on terminology: `proxy` is `CurrencyNetworkProxy`? `RecoverableController` is `UserAccount`? 

Q: Updates `ContractNetwork` == Updates `CurrencyNetwork` smart contract code [..] destination address of the `CurrencyNetwork` ? 

Why is a  `CurrencyNetworkProxy` created for every user account? That would imply, that all of them need to be updated to the new contract if it is changed. I thought the idea was to have global updates, by updating one contract.

**Comment by heikoheiko** [comment]
Data is strored within `CurrencyNetworkProxy` ?

**Comment by heikoheiko** [comment]
Issue description needs an update

**Comment by ice09** [comment]
So you imply using one Proxy for all `user-accounts`? Then it'd be

1. Only `user-account` is created on onboarding, wired to the generic `Proxy` then
2. `user-account` provides exchanging `app-account` in case of key lost
3. `Proxy` must use `DELEGATECALL` then, since its address is always the same (differs from image)
 
But: using this solution, `user-account` itself cannot be replaced if it is broken
To solve this, should be Proxy have a mapping of the keys which can use him, which then could be updated?

**Comment by heikoheiko** [comment]
When using Proxy please let's always specify what proxy it is. Assuming CurrencyNetworkProxy. Not sure if i'd call it a proxy. It's actually the CurrencyNetwork which has an updateable library. 

1. No. a `UserAccount` (please let's stick with one notation to reference it. i.e. the camel case contract name) works for multiple CurrencyNetworks. The currency network is part of the transaction data it forwards. 
2. I don't know what an app-account is. It does not support to update the EOA for now. Lost keys are handled by the requirement to backup the seed. 
3. i think yes. please link the pattern, that you plan to implement. 

Yes, using this solution user account can not be updated. Let's defer updatability of all components for now.

**Comment by andfletcher** [comment]
Outdated by freeze functionality
