### ISSUE TITLE
Close trustlines with pending interests

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/contracts#353]
It is not easy to close a trustline that has interests. You would need to bring the balance of the trustline down to 0, but by the time you send a transaction to pay out the debt, the value of the debt has changed due to interests.

You would thus need to remove the interests on the trustlines first, before settling it.

It is also unreliable to predict the interests that will be on the trustlines when you try to settle it as it depends on the block timestamp that is chosen by the validator / depends on whether a validator is skipped / depends on whether the next validator includes your tx in the block.

We can find a way to fix it, for example by adding a `closeTrustlineWithInterests` function that will allow some level of freedom on the balance to close a trustline. E.g. bringing a balance from `x` to `x * interests_rate * a_couple_minute` would bring it to `0` and allow closing it instead.

**Comment by andfletcher** [comment]
Important to consider if we create the 2.0 version of currency networks

**Comment by cducrest** [comment]
Close trustline with max balance

**Comment by cducrest** [comment]
Done
