### ISSUE TITLE
User is onboarded to Trustlines Network

### ISSUE THREAD

**Issue by ice09** [trustlines-protocol/contracts#8]
When a new user is onboarded, he has to get an unique indentity, ie. a `user-account` in the blockchain, next to his `app-account` in the mobile app.

## Rationale

If a user loses his mobile, his `app-account` is lost and he cannot access his `Trustlines` anymore. Therefore, a `user-account` must exist which delegates all calls to other contracts, overwriting the user's `msg.sender` with its own address. This way, a (on user-account-creation) predefined address can exchange the user's `app-account` address in the `user-account`, enabling the user to use a new `app-account` on an other mobile.

![image](https://user-images.githubusercontent.com/2828581/28818872-b8817db4-76ac-11e7-988e-f8ec43bb5d44.png) 

## Technical Requirements
- [ ] support `owner` (i.e. controlling EOA) as an initialization parameter (needed for onboarding)
- [ ] support setting the pubkey (so others know on which key to encrypt messages)

## Integration requirements
- [ ] integration test with real node (`parity --dev`)

**Comment by ice09** [comment]
- [ ] use uPort Proxy, possible?
- [ ] modify Proxy to call interface functions of `CurrencyNetwork.sol`, not arbitrary once
- [ ] integration test with real node (`parity --dev`)

**Comment by andfletcher** [comment]
Outdated since we implemented parts differently.
